### PR TITLE
Map sensors to display flights on a map card

### PR DESCRIPTION
**Pull request by jesmak**
- Added a new configuration option (Amount of map sensors to create)
- Added code to create and update map sensors
- Added Finnish localization
- Updated readme to reflect the changes, with an example map card configuration

### CODE REVIEW

**Comment by AlexandrErohin** [comment]
@jesmak Thank you for this work! I have tested it and I like that as it is a clear map with flight direction. But it has 2 problems
1) You if there are more flights then amount of sensors - some flights will not be displayed
2) These sensors consume memory

I have played with maps and what I have got:
map

Unfortunately, there are commercial labels that interfere (Your map more clean), but it doesnt require additional sensors

**Comment by jesmak** [comment]
Yup, that is a clear downside. Need to add a big number of sensors in a busy area, to avoid flights not being shown. It is in no way a perfect solution, but it works quite well in my less busy area.

By the way, you could probably get rid of the commercial tags with an adblocker. You can just block the annoying elements. Won't work with a mobile, but if you mainly use Home Assistant with a computer, that might make it pretty ok.

**Comment by AlexandrErohin** [comment]
@jesmak Hi
Could you update only [fi.json](https://github.com/AlexandrErohin/home-assistant-flightradar24/pull/10/files#diff-9e0104bcc1dbd766068fa25039ccb3fd1de7051a170aa50e3ad276363ee18253) - It would be great to add Finnish language

**Comment by jesmak** [comment]
> @jesmak Hi Could you update only [fi.json](https://github.com/AlexandrErohin/home-assistant-flightradar24/pull/10/files#diff-9e0104bcc1dbd766068fa25039ccb3fd1de7051a170aa50e3ad276363ee18253) - It would be great to add Finnish language

I can drop the PR and create a new one with just the localization.

**Pull request closed without merging**
